### ISSUE TITLE
在SAE上部署时出现了编码问题,Python版本3.5.1

### ISSUE THREAD

**Issue by steamTeufel** [doraemonext/wechat-python-sdk#104]
Collecting wechat-sdk==0.6.3 (from -r requirements.txt (line 3))
       Downloading http://pypi.douban.com/packages/db/c1/2bdd2f6d03e3ef2e77f2ae4ca13f298d3b64a5d623813afe055e1eeda61c/wechat-sdk-0.6.3.tar.gz (53kB)
       Complete output from command python setup.py egg_info:
       Traceback (most recent call last):
       File "<string>", line 20, in <module>
       File "/tmp/pip-build-_qxom3r2/wechat-sdk/setup.py", line 11, in <module>
       long_description=open("README.rst").read(),
       File "/app/.heroku/python/lib/python3.5/encodings/ascii.py", line 26, in decode
       return codecs.ascii_decode(input, self.errors)[0]
       UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
       
----------------------------------------

**Comment by doraemonext** [comment]
已经修正，v0.6.4
