### ISSUE TITLE
sae下，调用wechat-sdk报错：ImportError: cannot import name _AES

### ISSUE THREAD

**Issue by GreatMartial** [doraemonext/wechat-python-sdk#106]
Traceback (most recent call last):
  File "/data1/www/htdocs/910/weixintest1181/1/index.wsgi", line 11, in <module>
    from wechat_sdk import WechatConf
  File "/data1/www/htdocs/910/weixintest1181/1/vendor/wechat_sdk/**init**.py", line 3, in <module>
    from wechat_sdk.core.conf import WechatConf
  File "/data1/www/htdocs/910/weixintest1181/1/vendor/wechat_sdk/core/conf.py", line 7, in <module>
    from wechat_sdk.lib.crypto import BasicCrypto
  File "/data1/www/htdocs/910/weixintest1181/1/vendor/wechat_sdk/lib/crypto/**init**.py", line 3, in <module>
    from wechat_sdk.lib.crypto.cryptos import WechatBaseCrypto, BasicCrypto, CorpCrypto
  File "/data1/www/htdocs/910/weixintest1181/1/vendor/wechat_sdk/lib/crypto/cryptos.py", line 10, in <module>
    from wechat_sdk.lib.crypto.base import BaseCrypto
  File "/data1/www/htdocs/910/weixintest1181/1/vendor/wechat_sdk/lib/crypto/base.py", line 9, in <module>
    from Crypto.Cipher import AES
  File "/data1/www/htdocs/910/weixintest1181/1/vendor/Crypto/Cipher/AES.py", line 50, in <module>
    from Crypto.Cipher import _AES
ImportError: cannot import name _AES

 看到有人问过这个问题，回答是：调用sae预装的PyCrypto。
我在配置文件里添加了PyCrypto，但是从报错的路径来看，还是应用还是调用了wechat-sdk里的PyCrypto包。

本人小白一枚，请问具体该怎样解决？  希望将详细一些，谢谢

**Comment by Leonard-Peng** [comment]
同问

**Comment by cscyclone** [comment]
同问,求解

**Comment by xanahopper** [comment]
@GreatMartial 
1.如果你使用了vendor方法，在vendor安装完wechat-sdk之后，会自动安装PyCrypto包，进去把Crypto和pycrypto-xxxx-dist-info两个文件夹删掉
2.在config.yaml里，添加官方的PyCrypto 2.6的需求，因为默认PyCrypto是没有加载的

PS. 感觉SAE比BAE快很多……但是BAE比SAE方便很多
