### ISSUE TITLE
请基于wechat-python-sdk提供一个实例教程

### ISSUE THREAD

**Issue by wuyu3163** [doraemonext/wechat-python-sdk#41]
请基于wechat-python-sdk提供一个实例教程，尤其是基于我们这些初学者，没有实例不知道如何使用。

**Comment by hbrls** [comment]
你是说这个吗？http://wechat-python-sdk.readthedocs.org/zh_CN/master/tutorial.html

**Comment by wuyu3163** [comment]
建议在现有基础上增加URL及URL对应的VIEW实例.

**Comment by JohnnyZhao** [comment]
正有此意，接下来有课会做一个基于 Django 的 demo

**Comment by JohnnyZhao** [comment]
正有此意，接下来有时间会做一个基于 Django 的 demo

**Comment by xrlin** [comment]
有时间我可以写一个基于Flask框架的实用demo。

**Comment by cuikangyuan** [comment]
😄

**Comment by liuwons** [comment]
在GitHub上放了一个用```Tornado```和```wechat-python-sdk```搭建的聊天机器人公众号，用图灵机器人API回复用户的消息，其他功能也在扩充中。
GitHub仓库地址： [green](https://github.com/liuwons/green)

**Comment by djstava** [comment]
@hbrls The link is unavailable.

**Comment by longfengfirst** [comment]
推出一个基于django1.10的demo吧，调试了2天都没有成功！
[29/Sep/2016 06:56:08] "GET /wx?signature=0590557544deba728ddd84fb0170239657c61a2c&echostr=2927635854445772623&timestamp=1475132164&nonce=1923904153 HTTP/1.1" 200 19
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/site-packages/django/utils/log.py", line 173, in format
    if args[1][0] == '2':
IndexError: tuple index out of range
Logged from file basehttp.py, line 85
报错如上，目前还没有解决
