### ISSUE TITLE
SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### ISSUE THREAD

**Issue by alycq** [doraemonext/wechat-python-sdk#66]
I 160308 01:34:21 connectionpool:758] Starting new HTTPS connection (1): api.weixin.qq.com
[E 160308 01:34:22 web:1406] Uncaught exception POST /wechatcheck?signature=75e15237ad8c613306a3f36b7cade96b438d85aa&timestamp=1457372062&nonce=826836284 (101.226.103.72)
    HTTPServerRequest(protocol='https', host='app.tsingdata.com', method='POST', uri='/wechatcheck?signature=75e15237ad8c613306a3f36b7cade96b438d85aa&timestamp=1457372062&nonce=826836284', version='HTTP/1.0', remote_ip='101.226.103.72', headers={'Content-Length': '274', 'X-Scheme': 'https', 'Host': 'app.tsingdata.com', 'Accept': '_/_', 'User-Agent': 'Mozilla/4.0', 'Connection': 'close', 'Pragma': 'no-cache', 'X-Real-Ip': '101.226.103.72', 'Content-Type': 'text/xml'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1331, in _execute
        result = method(_self.path_args, *_self.path_kwargs)
      File "/var/marsapp/web/views/page.py", line 358, in post
        response = self.process(wechat, body_text)
      File "/var/marsapp/web/views/page.py", line 331, in process
        self.report_msg(message, wechat)
      File "/var/marsapp/web/views/page.py", line 305, in report_msg
        user_info = wechat.get_user_info(str(message.source))
      File "/usr/local/lib/python2.7/dist-packages/wechat_sdk/basic.py", line 533, in get_user_info
        verify=False
      File "/usr/local/lib/python2.7/dist-packages/wechat_sdk/lib/request.py", line 72, in get
        *_kwargs
      File "/usr/local/lib/python2.7/dist-packages/wechat_sdk/lib/request.py", line 30, in request
        access_token = self.__conf.access_token if self.__conf is not None else access_token
      File "/usr/local/lib/python2.7/dist-packages/wechat_sdk/core/conf.py", line 156, in access_token
        self.grant_access_token()  # 从腾讯服务器获取 access token 并更新
      File "/usr/local/lib/python2.7/dist-packages/wechat_sdk/core/conf.py", line 208, in grant_access_token
        access_token=self.__access_token
      File "/usr/local/lib/python2.7/dist-packages/wechat_sdk/lib/request.py", line 72, in get
        *_kwargs
      File "/usr/local/lib/python2.7/dist-packages/wechat_sdk/lib/request.py", line 46, in request
        *_kwargs
      File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 53, in request
        return session.request(method=method, url=url, *_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
        resp = self.send(prep, *_send_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
        r = adapter.send(request, *_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 447, in send
        raise SSLError(e, request=request)
    SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

为什么会出现这个问题？是因为我的网站使用的是HTTPS，然后跟微信之间校验CA证书有问题么？应该怎么处理？谢谢！

**Comment by mynameischaos** [comment]
简单解决办法：代码中相应位置的 requests.request()  其中添加参数 verify=False； 意思是不验证；
也就是requests.request(... , verify=False)

**Comment by fengdy** [comment]
在调用sdk自带的发送模板消息时, 也报类似错误,bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],) 这如何解决

**Comment by mynameischaos** [comment]
直接找到sdk的代码修改即可呀~    /usr/local/lib/python2.7/dist-packages/wechat_sdk/lib/request.py
中 def request(self, method, url, access_token=None,verify=False, **kwargs) ；  requests.request(添加参数verify=verify)  self.request(verify=False); 所有python 的request中都加这个参数即可

**Comment by linmounong** [comment]
verify=False就是自废武功啊……
我遇到过类似问题，可能是缺少一些库。如果你使用flask，可以根据这几个关键词找找原因

* pyopenssl
* snimissingwarning

**Comment by leiqin** [comment]
我在本机没有遇到这个问题，但是在 centos7 的 docker 中遇到相同的问题，我用这个命令解决了它
`cat /etc/ssl/certs/ca-bundle.crt >>$(python -c 'import requests; print requests.certs.where()')`
