### ISSUE TITLE
pip 安装编码错误，无法安装

### ISSUE THREAD

**Issue by ykbj** [doraemonext/wechat-python-sdk#88]
Collecting wechat-sdk
  Using cached wechat-sdk-0.6.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\yk100\AppData\Local\Temp\pip-build-2im9121z\wechat-sdk\setup.py", line 11, in <module>
        long_description=open("README.rst").read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 2: illegal multibyte sequence

    ----------------------------------------

**Comment by BiaoLiu** [comment]
同样碰到这个问题

**Comment by doraemonext** [comment]
已更新。
